### ISSUE TITLE
[Error Submission] Error 110-3300

### ISSUE THREAD

**Issue by guusbuk** [nh-server/Kurisu#1112] opened 2022-07-31 16:07 UTC
**Console**

Wii U

**Error Code**

110-3300

**Error Description**

There is no information to display (roughly translated. Original is 'Er kan geen informatie worden weergegeven')
https://www.reddit.com/r/wiiu/comments/32rbgs/eshop_error_1103300_when_clicking_on_special/ 
When opening the eshop and clicking on Mario or Zelda (I think because you open a page without any games.

**Comment by lifehackerhansol** [comment] 2024-07-17 22:53
Duplicate of #1084.

Your own issue, even...

**Closed by lifehackerhansol** 2024-07-17 22:53 UTC
