### ISSUE TITLE
[Error Submission] Error 001-0502

### ISSUE THREAD

**Issue by thedryramen** [nh-server/Kurisu#1185] opened 2023-04-17 01:53 UTC
**Console**

New 2DS xl

**Error Code**

001-0502

**Error Description**

"Unable to connect to the server.
Please try again later."

I am trying to soft-mod my 2DS xl following the 3ds.guide instructions. I cannot access the friends list function to connect with bruteforce moveable. My console has interet connection, but is getting a connection error only with the friends list app. I have tried on different days and with different Wi-Fi networks. I have tried adding 8.8.8.8 as a secondary DNS for my home Wi-Fi, and I have also tried connecting to my iPhone hotspot but the issue persists.

**Comment by lifehackerhansol** [comment] 2024-07-17 22:34
Duplicate of https://github.com/nh-server/Kurisu/issues/1183

**Closed by lifehackerhansol** 2024-07-17 22:34 UTC
